name: build mele-a200 image

on:
  push:
    branches: [ "master" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Checkout armbian/build
        run: |
          git clone --depth=1 --branch=main https://github.com/mofeng-git/build

      - name: Patch Mele A200
        run: |          
          cat <<EOF > ./build/config/boards/onecloud
          BOARD_NAME="S812"
          BOARDFAMILY="aml-s812"
          BOOTCONFIG="linux-aml-s812-current.config"
          KERNEL_TARGET="current,edge"
          EOF

      - name: Build for mele-a200
        run: |
          cd build
          ./compile.sh build BOARD=aml-s812 BRANCH=current BUILD_MINIMAL=yes KERNEL_CONFIGURE=no RELEASE=jammy FORCE_CHECK_MD5_PACKAGES=no

      - uses: actions/upload-artifact@v4
        with:
          name: built-images
          path: build/output/images
