name: build onecloud image

on:
  push:
    branches: [ "master" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-20.04
    container: ghcr.io/armbian/docker-armbian-build:armbian-ubuntu-jammy-latest
    steps:

      - name: Checkout armbian/build
        run: |
          git clone --depth=1 --branch=main https://github.com/hy5528/Build


      - name: Build for aml-s812
        run: |
          cd Build
          sudo ./compile.sh  BOARD=onecloud BRANCH=legacy RELEASE=jammy BUILD_MINIMAL=yes BUILD_DESKTOP=no  KERNEL_CONFIGURE=no COMPRESS_OUTPUTIMAGE=sha,gpg,img DOWNLOAD_MIRROR=china MAINLINE_MIRROR=tuna EXTRAWIFI=no
      - name: Build burn for aml-s812
        run: |
          cd Build
          sudo ./userpatches/burnimg-pack.sh output/images/Armbian_24.03_Aml-s812_jammy_current_5.9.0-rc7_minimal.img

      - uses: actions/upload-artifact@v4
        with:
          name: built-images
          path: Build-Armbian/output/images/
