name: build onecloud image

on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
      - name: Maximize build space
        uses: easimon/maximize-build-space@master
        with:
          # 这个值是保留给系统的空间大小，之前设置太小，总会在安装依赖或者编译过程中报设备空间不足的错误而导致编译失败
          root-reserve-mb: 18096
          swap-size-mb: 2266
          remove-dotnet: 'true'
          remove-android: 'true'
      
      - name: Checkout armbian/build
        run: |
          git clone https://github.com/witallwang/Build-Armbian
          
      - name: Build for onecloud
        run: |
          cd Build-Armbian
          ./compile.sh BOARD="odroidxu4" BRANCH="current" RELEASE="bullseye" KERNEL_ONLY="no" KERNEL_CONFIGURE="no" BUILD_DESKTOP="no" BUILD_MINIMAL="yes"
      - uses: softprops/action-gh-release@v2.0.4
        with:
          name: built-images
          path: build/output/images
