
name: build mele-a200 image

on:
  push:
    branches: [ "master" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-24.04
    container: ghcr.io/armbian/docker-armbian-build:armbian-ubuntu-jammy-latest
    steps:
      - uses: actions/checkout@v3

      - name: Checkout armbian/build
        run: |
          git clone --depth=1 --branch=main https://github.com/mofeng-git/build
      - name: Build for mele-a200
        run: |
          cd build
          sudo ./compile.sh build BOARD=onecloud BRANCH=legacy BUILD_DESKTOP=no BUILD_MINIMAL=yes COMPRESS_OUTPUTIMAGE=img EXTRAWIFI=yes  KERNEL_CONFIGURE=no  DOWNLOAD_MIRROR=china MAINLINE_MIRROR=tuna RELEASE=jammy BOOTSIZE=64  SYNC_CLOCK=no INCLUDE_HOME_DIR=yes  KERNEL_COMPILER=/home/mofeng/code/toolchain/gcc-arm-9.2-2019.12-x86_64-arm-none-linux-gnueabihf/bin/arm-none-linux-gnueabihf-

      - uses: actions/upload-artifact@v4
        with:
          name: built-images
          path: build/output/images

