
name: build mele-a200 image

on:
  push:
    branches: [ "master" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: debian-11
    
    steps:
      - uses: actions/checkout@v3

      - name: Checkout armbian/build
        run: |
          git clone --depth=1 --branch=master https://github.com/witallwang/Build-Armbian
      - name: Build for mele-a200
        run: |
          cd Build-Armbian
          sudo ./compile.sh BOARD="aml-s812" BRANCH="current" RELEASE="bullseye" KERNEL_ONLY="no" KERNEL_CONFIGURE="no" BUILD_DESKTOP="no" BUILD_MINIMAL="yes"

      - uses: actions/upload-artifact@v4
        with:
          name: built-images
          path: build/output/images

