name: build OneCloud image

on:
  push:
    branches: [ "master" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Checkout armbian/build
        run: |
          git clone --depth=1 --branch=main https://github.com/mofeng-git/build

      - name: Patch OneCloud
        run: |          
          cat <<EOF > ./build/config/boards/onecloud.conf
          BOARD_NAME="OneCloud"
          BOARDFAMILY="meson8b"
          BOARD_MAINTAINER="hzyitc"
          KERNEL_TARGET="legacy,current,edge"

          BOOTCONFIG="none"
          BOOTSCRIPT="boot-onecloud.cmd:boot.cmd"
          BOOTENV_FILE="onecloud.txt"

          OFFSET="16"
          BOOTSIZE="64"
          BOOTFS_TYPE="fat"
          EOF

      - name: Build for OneCloud
        run: |
          cd build
          ./compile.sh build BOARD=onecloud BRANCH=legacy BUILD_DESKTOP=no BUILD_MINIMAL=yes COMPRESS_OUTPUTIMAGE=img EXTRAWIFI=yes  KERNEL_CONFIGURE=no  DOWNLOAD_MIRROR=china MAINLINE_MIRROR=tuna RELEASE=jammy BOOTSIZE=64  SYNC_CLOCK=no INCLUDE_HOME_DIR=yes 
      - uses: actions/upload-artifact@v4
        with:
          name: built-images
          path: build/output/images
